#!/bin/bash
# ls
alias ls="ls --color=always"
alias sl=ls
alias ll='ls -lh'
alias la='ls -lha'
alias l='ls -lha'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias lg='ls --color=always | grep --color=always -i'

alias c='clear'
alias q="exit"
alias h='history'

# tree
alias tree="find . -print | sed -e 's;[^/]*/;|___;g;s;___|; |;g'"

# directory
alias md='mkdir -p'
alias rd=rmdir
alias d='dirs -v'

# open the last edited file
alias lvim="vim -c \"normal '0\""

# generate timestamp
alias timestamp='date "+%Y%m%d%H%M%S"'

# grep for running process
alias psg='ps ax | grep -v grep | grep '
alias df='df -h'
alias less='less -W'
alias lf='less -i +F'

# generate dir with actual timestamp
alias tsdir='timestamp | xargs mkdir'

# shortcuts
alias update='sudo apt-get update && sudo apt-get upgrade'
alias apt-get='sudo apt-get'
alias agi='sudo apt-get install'
alias acs='apt-cache search'

# Extract commands
alias untargz="tar xvzf"
alias untarbz2="tar xvjf"

alias gc="git commit -m"
alias gca="git commit -am"
alias gs="git status -sb"
alias gd="git diff"
alias gitcommitcount="git shortlog -s -n --no-merges"

# gemsets
alias gemset-active="rbenv gemset active"
alias gemset-list="rbenv gemset list"

# rails stuff
alias railsdb="bundle exec rake db:drop && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed"
